import "./handlers/configHandlers"
import "./handlers/gameHandlers"
import "./handlers/modsHandlers"
import "./handlers/pathsHandlers"
import "./handlers/utilsHandlers"
import "./handlers/netHandlers"
import "./handlers/appUpdaterHandlers"
